{{- $root := . -}}
{{- range $key, $svc := .Values.services }}
{{- if and $svc.hpa $svc.hpa.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "my-family.fullname" $root }}-{{ $svc.name }}
  labels:
    {{- include "my-family.labels" $root | nindent 4 }}
    app.kubernetes.io/name: {{ $svc.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "my-family.fullname" $root }}-{{ $svc.name }}
  minReplicas: {{ $svc.hpa.minReplicas }}
  maxReplicas: {{ $svc.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $svc.hpa.targetCPUUtilization }}
{{- end }}
{{- end }}
