{{- $root := . -}}
{{- range $key, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-family.fullname" $root }}-{{ $svc.name }}
  labels:
    {{- include "my-family.labels" $root | nindent 4 }}
    app.kubernetes.io/name: {{ $svc.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $svc.port }}
      targetPort: svc-port
      protocol: TCP
      name: svc-port
  selector:
    app.kubernetes.io/name: {{ $svc.name }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
{{- end }}
